apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ju0p
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0003-tenant/ci1t-830-0003-app/devfile-sample-ju0p@sha256:008a2fce7855ee05ac3c0193bb543ee83efc98e0ea88b447778633d63298a187
        name: my-nodejs
        resources: {}
status: {}
